[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.format]
command = "cargo"
args = ["fmt"]

[tasks.clippy]
command = "cargo"
args = ["clippy"]

[tasks.lint]
dependencies = [
    "format",
    "clippy",
]

[tasks.cargo-test]
command = "cargo"
args = ["test"]

[tasks.test]
dependencies = [
    "lint",
    "cargo-test",
]

[tasks.wasm-build]
script = ["bash scripts/build-wasm.sh --dev"]

[tasks.wasm-release-build]
script = ["bash scripts/build-wasm.sh"]
